server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/graduation?serverTimezone=UTC&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    maxActive: 20
    initialSize: 5
    maxWait: 60000  #最大超过时间
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j2
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8   #编码
    prefix: classpath:/templates/   #前缀
    cache: false  #是否使用缓存
    suffix: .html #后缀名
  aop:  #开启spring boot aop
    auto: true
    proxy-target-class: true


mybatis:
  mapper-locations: classpath:Mapper/**/*.xml
  type-aliases-package: com.example.demo.Graduation.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




logging:
  config: classpath:log4j2.xml
  level:
    com.example.demo: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
